version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: injury-postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5433:5432'
    networks:
      - my_network

  broker:
    image: apache/activemq-artemis:latest
    container_name: apache-artemis
    restart: always
    environment:
      - APACHE_USER=artemis
      - APACHE_PASSWORD=artemis

    ports:
      - '8161:8161'
      - '61616:61616'


networks:
  my_network: